# Import, Clean and Analyse Data

## Import Libs

In [3]:
#Libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Reading Dataset

In [4]:
stats_regular = pd.read_csv('.../2022-2023 NBA Player Stats - Regular.csv', delimiter = ';', index_col = 'Rk', encoding = 'ISO-8859-1')

stats_playoffs = pd.read_csv('.../2022-2023 NBA Player Stats - Playoffs.csv', delimiter = ';', index_col = 'Rk', encoding = 'ISO-8859-1')

### Regular Season

In [5]:
df_stats_regular = stats_regular
df_stats_regular.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,0.485,...,0.702,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2
2,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,0.597,...,0.364,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6
3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,0.540,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,0.427,...,0.812,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9
5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,0.470,...,0.750,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0

In [6]:
df_stats_regular.info()

<class 'pandas.core.frame.DataFrame'>
Index: 679 entries, 1 to 539
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  679 non-null    object
 1   Pos     679 non-null    object
 2   Age     679 non-null    int64
 3   Tm      679 non-null    object
 4   G       679 non-null    int64
 5   GS      679 non-null    int64
 6   MP      679 non-null    float64
 7   FG      679 non-null    float64
 8   FGA     679 non-null    float64
 9   FG%     679 non-null    float64
 10  3P      679 non-null    float64
 11  3PA     679 non-null    float64
 12  3P%     679 non-null    float64
 13  2P      679 non-null    float64
 14  2PA     679 non-null    float64
 15  2P%     679 non-null    float64
 16  eFG%    679 non-null    float64
 17  FT      679 non-null    float64
 18  FTA     679 non-null    float64
 19  FT%     679 non-null    float64
 20  ORB     679 non-null    float64
 21  DRB     679 non-null    float64
 22  TRB     679 non-null    float64
 23  AST     679 non-null    float64
 24  STL     679 non-null    float64
 25  BLK     679 non-null    float64
 26  TOV     679 non-null    float64
 27  PF      679 non-null    float64
 28  PTS     679 non-null    float64
dtypes: float64(23), int64(3), object(3)
memory usage: 159.1+ KB

In [7]:
df_stats_regular.describe()

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,...,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000,679.000000
mean,26.025037,43.338733,20.069219,19.463476,3.249190,6.920913,0.462190,0.996465,2.782916,0.318141,...,0.711576,0.842268,2.620177,3.461414,2.011635,0.601767,0.370398,1.067305,1.660677,8.858763
std,4.325709,24.727306,25.766359,9.416316,2.362645,4.795709,0.116682,0.862161,2.209427,0.139918,...,0.224774,0.731867,1.715999,2.281317,1.891472,0.392063,0.367514,0.799478,0.770492,6.631226
min,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,22.000000,0.000000,12.150000,1.500000,3.400000,0.415000,0.300000,1.000000,0.286000,...,0.667000,0.300000,1.400000,1.800000,0.800000,0.300000,0.100000,0.500000,1.200000,4.100000
50%,25.000000,45.000000,6.000000,18.800000,2.600000,5.700000,0.454000,0.800000,2.400000,0.346000,...,0.760000,0.700000,2.300000,3.000000,1.300000,0.500000,0.300000,0.900000,1.600000,6.900000
75%,29.000000,65.500000,36.500000,27.550000,4.200000,9.200000,0.505000,1.500000,4.150000,0.388000,...,0.841000,1.100000,3.400000,4.500000,2.700000,0.800000,0.500000,1.400000,2.200000,11.550000
max,42.000000,83.000000,83.000000,41.000000,11.200000,22.200000,1.000000,4.900000,11.400000,1.000000,...,1.000000,5.100000,9.600000,12.500000,10.700000,3.000000,3.000000,4.100000,5.000000,33.100000

In [8]:
df_stats_regular.columns.tolist()

['Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

### Playoffs Season

In [9]:
df_stats_playoffs = stats_playoffs
df_stats_playoffs.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Bam Adebayo,C,25,MIA,23,23,37.0,7.3,15.1,0.481,...,0.821,2.7,7.1,9.9,3.7,0.9,0.7,2.7,3.1,17.9
2,Santi Aldama,PF,22,MEM,6,0,16.8,2.5,5.5,0.455,...,1.000,1.2,3.2,4.3,1.2,0.5,0.0,0.3,0.8,6.5
3,Nickeil Alexander-Walker,SG,24,MIN,5,4,29.6,3.0,7.0,0.429,...,0.667,0.2,1.8,2.0,1.4,0.6,0.2,0.8,1.8,8.4
4,Grayson Allen,SG,27,MIL,5,5,29.8,3.8,8.2,0.463,...,0.857,0.2,2.2,2.4,1.8,0.4,0.0,0.8,1.4,11.6
5,Jarrett Allen,C,24,CLE,5,5,38.2,4.4,7.2,0.611,...,0.500,3.0,4.4,7.4,2.4,0.8,1.0,0.6,2.0,9.4

In [10]:
df_stats_playoffs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 217 entries, 1 to 217
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  217 non-null    object
 1   Pos     217 non-null    object
 2   Age     217 non-null    int64
 3   Tm      217 non-null    object
 4   G       217 non-null    int64
 5   GS      217 non-null    int64
 6   MP      217 non-null    float64
 7   FG      217 non-null    float64
 8   FGA     217 non-null    float64
 9   FG%     217 non-null    float64
 10  3P      217 non-null    float64
 11  3PA     217 non-null    float64
 12  3P%     217 non-null    float64
 13  2P      217 non-null    float64
 14  2PA     217 non-null    float64
 15  2P%     217 non-null    float64
 16  eFG%    217 non-null    float64
 17  FT      217 non-null    float64
 18  FTA     217 non-null    float64
 19  FT%     217 non-null    float64
 20  ORB     217 non-null    float64
 21  DRB     217 non-null    float64
 22  TRB     217 non-null    float64
 23  AST     217 non-null    float64
 24  STL     217 non-null    float64
 25  BLK     217 non-null    float64
 26  TOV     217 non-null    float64
 27  PF      217 non-null    float64
 28  PTS     217 non-null    float64
dtypes: float64(23), int64(3), object(3)
memory usage: 50.9+ KB

In [11]:
df_stats_playoffs.describe()

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,...,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000
mean,27.050691,7.963134,3.870968,19.607373,3.193548,7.073272,0.399438,0.966820,2.815207,0.257590,...,0.576336,0.833180,2.605530,3.436866,1.879263,0.551152,0.379263,1.031336,1.626267,8.699078
std,4.402463,5.848277,5.884847,13.217481,3.042653,6.380738,0.197246,0.992894,2.603505,0.211215,...,0.368579,0.955736,2.332136,3.080874,2.170826,0.531256,0.491769,1.062899,1.112430,8.375692
min,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,4.000000,0.000000,6.000000,0.800000,1.900000,0.345000,0.000000,0.500000,0.000000,...,0.000000,0.100000,0.800000,1.000000,0.300000,0.000000,0.000000,0.300000,0.700000,2.000000
50%,26.000000,6.000000,0.000000,18.600000,2.400000,5.000000,0.429000,0.700000,2.400000,0.302000,...,0.722000,0.600000,2.000000,2.600000,1.000000,0.500000,0.200000,0.700000,1.700000,6.500000
75%,30.000000,11.000000,5.000000,30.900000,5.000000,10.300000,0.500000,1.700000,4.600000,0.380000,...,0.860000,1.200000,4.100000,5.300000,2.600000,0.800000,0.500000,1.400000,2.500000,12.700000
max,42.000000,23.000000,23.000000,42.400000,12.800000,24.800000,1.000000,4.400000,12.100000,1.000000,...,1.000000,5.000000,11.700000,14.100000,10.200000,2.100000,3.100000,4.700000,4.800000,34.500000

In [12]:
df_stats_playoffs.columns.tolist()

['Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

## Checking for duplicates

### Regular Season

In [13]:
df_stats_regular.nunique()

Player    539
Pos         8
Age        22
Tm         31
G          83
GS         80
MP        308
FG        101
FGA       174
FG%       279
3P         40
3PA        92
3P%       214
2P         83
2PA       134
2P%       273
eFG%      275
FT         67
FTA        80
FT%       263
ORB        39
DRB        79
TRB       101
AST        83
STL        22
BLK        22
TOV        40
PF         40
PTS       223
dtype: int64

In [14]:
duplicate_rows_df = df_stats_regular[df_stats_regular.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 29)

### Playoff Season

In [15]:
df_stats_playoffs.nunique()

Player    217
Pos         5
Age        21
Tm         16
G          21
GS         20
MP        146
FG         77
FGA       118
FG%       120
3P         32
3PA        73
3P%        93
2P         68
2PA        97
2P%       104
eFG%      129
FT         48
FTA        55
FT%        74
ORB        34
DRB        67
TRB        82
AST        64
STL        21
BLK        21
TOV        40
PF         38
PTS       129
dtype: int64

In [16]:
duplicate_rows_df = df_stats_playoffs[df_stats_playoffs.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 29)

## Checking Missing Values

### Regular Season

In [17]:
df_stats_regular.isnull().sum()

Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
dtype: int64

### Playoff Season

In [18]:
df_stats_playoffs.isnull().sum()

Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
dtype: int64

## Analyse NBA Stats Regular Season

In [19]:
df_stats_regular. head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,0.485,...,0.702,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2
2,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,0.597,...,0.364,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6
3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,0.540,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,0.427,...,0.812,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9
5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,0.470,...,0.750,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0

#### Corrigindo jogadores que jogam em mais de uma posiÃ§Ã£o

In [20]:
df_stats_regular['Pos'] = df_stats_regular['Pos'].apply(lambda x: x.split('-')[0] if '-' in x else x)

#### Filtrando os Dataframes para analisar por posiÃ§Ã£o

In [21]:

df_stats_regular_pg = df_stats_regular[df_stats_regular['Pos'] == 'PG'][['Player', 'Pos', 'PTS', 'AST','STL','TOV']]
df_stats_regular_sg = df_stats_regular[df_stats_regular['Pos'] == 'SG'][['Player', 'Pos', 'PTS', '3P%', 'STL', 'TRB']]
df_stats_regular_sf = df_stats_regular[df_stats_regular['Pos'] == 'SF'][['Player', 'Pos', 'PTS', 'TRB', 'AST', 'STL']]
df_stats_regular_pf = df_stats_regular[df_stats_regular['Pos'] == 'PF'][['Player', 'Pos', 'TRB', 'PTS', 'BLK', '2P%']]
df_stats_regular_c = df_stats_regular[df_stats_regular['Pos'] == 'C'][['Player', 'Pos', 'TRB', 'BLK', 'PTS', '2P%']]

#### Rankeando os jogadores

In [22]:

df_stats_regular_pg_sorted = df_stats_regular_pg.sort_values(by=['PTS', 'AST','STL','TOV'], ascending=[False, False, False, True])
df_stats_regular_sg_sorted = df_stats_regular_sg.sort_values(by=['PTS', '3P%', 'STL', 'TRB'], ascending=[False, False, False, False])
df_stats_regular_sf_sorted = df_stats_regular_sf.sort_values(by=['PTS', 'TRB', 'AST', 'STL'], ascending=[False, False, False, False])
df_stats_regular_pf_sorted = df_stats_regular_pf.sort_values(by=['TRB', 'PTS', 'BLK', '2P%'], ascending=[False, False, False, False])
df_stats_regular_c_sorted = df_stats_regular_c.sort_values(by=['TRB', 'BLK', 'PTS', '2P%'], ascending=[False, False, False, False])

#### Selecionando os melhores da Regular Season

In [23]:
df_best_regular_pg = df_stats_regular_pg_sorted.loc[df_stats_regular_pg_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_regular_sg = df_stats_regular_sg_sorted.loc[df_stats_regular_sg_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_regular_sf = df_stats_regular_sf_sorted.loc[df_stats_regular_sf_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_regular_pf = df_stats_regular_pf_sorted.loc[df_stats_regular_pf_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_regular_c = df_stats_regular_c_sorted.loc[df_stats_regular_c_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_regular_players = pd.concat([df_best_regular_pg, df_best_regular_sg, df_best_regular_sf, df_best_regular_pf, df_best_regular_c])

df_best_regular_players.head(5)

                    Player Pos   PTS
Rk
125            Luka Don?i?  PG  32.4
338       Donovan Mitchell  SG  28.3
64            Jaylen Brown  SF  26.6
11   Giannis Antetokounmpo  PF  31.1
110          Anthony Davis   C  25.9

## Analisando Playoffs

In [24]:

df_stats_playoffs.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Bam Adebayo,C,25,MIA,23,23,37.0,7.3,15.1,0.481,...,0.821,2.7,7.1,9.9,3.7,0.9,0.7,2.7,3.1,17.9
2,Santi Aldama,PF,22,MEM,6,0,16.8,2.5,5.5,0.455,...,1.000,1.2,3.2,4.3,1.2,0.5,0.0,0.3,0.8,6.5
3,Nickeil Alexander-Walker,SG,24,MIN,5,4,29.6,3.0,7.0,0.429,...,0.667,0.2,1.8,2.0,1.4,0.6,0.2,0.8,1.8,8.4
4,Grayson Allen,SG,27,MIL,5,5,29.8,3.8,8.2,0.463,...,0.857,0.2,2.2,2.4,1.8,0.4,0.0,0.8,1.4,11.6
5,Jarrett Allen,C,24,CLE,5,5,38.2,4.4,7.2,0.611,...,0.500,3.0,4.4,7.4,2.4,0.8,1.0,0.6,2.0,9.4

#### Filtrando os Dataframes para analisar por posiÃ§Ã£o

In [25]:

df_stats_playoffs_pg = df_stats_playoffs[df_stats_playoffs['Pos'] == 'PG'][['Player', 'Pos', 'PTS', 'AST','STL','TOV']]
df_stats_playoffs_sg = df_stats_playoffs[df_stats_playoffs['Pos'] == 'SG'][['Player', 'Pos', 'PTS', '3P%', 'STL', 'TRB']]
df_stats_playoffs_sf = df_stats_playoffs[df_stats_playoffs['Pos'] == 'SF'][['Player', 'Pos', 'PTS', 'TRB', 'AST', 'STL']]
df_stats_playoffs_pf = df_stats_playoffs[df_stats_playoffs['Pos'] == 'PF'][['Player', 'Pos', 'TRB', 'PTS', 'BLK', '2P%']]
df_stats_playoffs_c = df_stats_playoffs[df_stats_playoffs['Pos'] == 'C'][['Player', 'Pos', 'TRB', 'BLK', 'PTS', '2P%']]

#### Rankeando os jogadores

In [26]:

df_stats_playoffs_pg_sorted = df_stats_playoffs_pg.sort_values(by=['PTS', 'AST','STL','TOV'], ascending=[False, False, False, True])
df_stats_playoffs_sg_sorted = df_stats_playoffs_sg.sort_values(by=['PTS', '3P%', 'STL', 'TRB'], ascending=[False, False, False, False])
df_stats_playoffs_sf_sorted = df_stats_playoffs_sf.sort_values(by=['PTS', 'TRB', 'AST', 'STL'], ascending=[False, False, False, False])
df_stats_playoffs_pf_sorted = df_stats_playoffs_pf.sort_values(by=['TRB', 'PTS', 'BLK', '2P%'], ascending=[False, False, False, False])
df_stats_playoffs_c_sorted = df_stats_playoffs_c.sort_values(by=['TRB', 'BLK', 'PTS', '2P%'], ascending=[False, False, False, False])

#### Selecionando os melhores jogadores do Playoff

In [28]:
df_best_playoffs_pg = df_stats_playoffs_pg_sorted.loc[df_stats_playoffs_pg_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_playoffs_sg = df_stats_playoffs_sg_sorted.loc[df_stats_playoffs_sg_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_playoffs_sf = df_stats_playoffs_sf_sorted.loc[df_stats_playoffs_sf_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_playoffs_pf = df_stats_playoffs_pf_sorted.loc[df_stats_playoffs_pf_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_playoffs_c = df_stats_playoffs_c_sorted.loc[df_stats_playoffs_c_sorted.index[0:1], ['Player', 'Pos', 'PTS']]
df_best_playoffs_players = pd.concat([df_best_playoffs_pg, df_best_playoffs_sg, df_best_playoffs_sf, df_best_playoffs_pf, df_best_playoffs_c])

df_best_playoffs_players.head(5)

                    Player Pos   PTS
Rk
48           Stephen Curry  PG  30.5
21            Devin Booker  SG  33.7
114          Kawhi Leonard  SF  34.5
7    Giannis Antetokounmpo  PF  23.3
49           Anthony Davis   C  22.6